services:
  - type: web
    name: halaltrade-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
